/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCell: typeof import('./components/common/ActionCell.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AssuntoCreate: typeof import('./components/assunto/AssuntoCreate.vue')['default']
    AssuntoForm: typeof import('./components/assunto/AssuntoForm.vue')['default']
    AssuntoList: typeof import('./components/assunto/AssuntoList.vue')['default']
    AssuntoShow: typeof import('./components/assunto/AssuntoShow.vue')['default']
    AssuntoUpdate: typeof import('./components/assunto/AssuntoUpdate.vue')['default']
    AutorCreate: typeof import('./components/autor/AutorCreate.vue')['default']
    AutorForm: typeof import('./components/autor/AutorForm.vue')['default']
    AutorList: typeof import('./components/autor/AutorList.vue')['default']
    AutorShow: typeof import('./components/autor/AutorShow.vue')['default']
    AutorUpdate: typeof import('./components/autor/AutorUpdate.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    ConfirmDelete: typeof import('./components/common/ConfirmDelete.vue')['default']
    DataFilter: typeof import('./components/common/DataFilter.vue')['default']
    FormRepeater: typeof import('./components/common/FormRepeater.vue')['default']
    GreetingCreate: typeof import('./components/greeting/GreetingCreate.vue')['default']
    GreetingForm: typeof import('./components/greeting/GreetingForm.vue')['default']
    GreetingList: typeof import('./components/greeting/GreetingList.vue')['default']
    GreetingShow: typeof import('./components/greeting/GreetingShow.vue')['default']
    GreetingUpdate: typeof import('./components/greeting/GreetingUpdate.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LivroCreate: typeof import('./components/livro/LivroCreate.vue')['default']
    LivroForm: typeof import('./components/livro/LivroForm.vue')['default']
    LivroList: typeof import('./components/livro/LivroList.vue')['default']
    LivroShow: typeof import('./components/livro/LivroShow.vue')['default']
    LivroUpdate: typeof import('./components/livro/LivroUpdate.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./components/common/Toolbar.vue')['default']
  }
}
